version: '3'
services:
  sandbox:
    build:
      context: ./sandbox
      dockerfile: Dockerfile
    environment: 
      HOST: 0.0.0.0
      PORT: 3000
      QUEUE_SIZE: 3
      ENV_NAME: local
    volumes:
      - ./sandbox:/server/